# Generated by Django 4.0.1 on 2022-01-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skillimage/')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('time', models.DateTimeField(blank=True, default='')),
            ],
        ),
    ]
